name: Semantic Version Tagging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get source branch name
        id: get_branch
        run: |
          echo "PR_BRANCH=unknown" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          else
            # For push events, get the last commit message branch info fallback
            BRANCH_NAME=$(git log -1 --pretty=%B | grep -oP '(feat|fix|rel)/[^\s]+')
            echo "PR_BRANCH=${BRANCH_NAME:-unknown}" >> $GITHUB_OUTPUT
          fi

      - name: Decide bump type based on branch prefix
        id: bump_type
        run: |
          BRANCH=${{ steps.get_branch.outputs.PR_BRANCH }}
          echo "Branch detected: $BRANCH"
          if [[ "$BRANCH" == feat/* ]]; then
            echo "bump=minor" >> $GITHUB_ENV
          elif [[ "$BRANCH" == fix/* ]]; then
            echo "bump=patch" >> $GITHUB_ENV
          elif [[ "$BRANCH" == rel/* ]]; then
            echo "bump=major" >> $GITHUB_ENV
          else
            echo "bump=patch" >> $GITHUB_ENV
          fi
          echo "Bump type set to $bump"

      - name: Bump version and create tag
        id: bump_version
        uses:  'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: "v"
          bump: ${{ env.bump }}
          create-tag: true
          push-tag: true
